name: Comment Coverage Report

on:
  workflow_run:
    workflows: ["Code Coverage Report Analysis"]
    types: [completed]

jobs:
  comment_coverage:
    name: Comment Coverage Report on PR
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Get PR information
        uses: potiuk/get-workflow-origin@v1_3
        id: source-run-info
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}

      - name: Download Coverage Report
        uses: dawidd6/action-download-artifact@v3
        with:
          name: coverage-report-for-comment
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        if: steps.source-run-info.outputs.pullRequestNumber != ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ steps.source-run-info.outputs.pullRequestNumber }}
          body-path: 'CoverageReport.md'