name: Comment Coverage Report

on:
  workflow_run:
    workflows: ["Code Coverage Report Analysis"]
    types: [completed]

jobs:
  comment_coverage:
    name: Comment Coverage Report on PR
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Download Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report-for-comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Get PR Number by Branch
        id: get-pr-number
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.payload.workflow_run.head_branch;
            const { owner, repo } = context.repo;

            let pr = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner,
              repo,
              commit_sha: context.payload.workflow_run.head_sha,
            });

            if (pr.data.length === 0) {
              pr = await github.rest.pulls.list({
                owner,
                repo,
                head: `${owner}:${branch}`,
                state: 'open'
              });
            }

            if (pr.data.length === 0) {
              core.setFailed('No PR found for this workflow run');
              return;
            }

            core.setOutput('pr_number', pr.data[0].number);

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ steps.get-pr-number.outputs.pr_number }}
          body-path: 'CoverageReport.md'
