# Contains job for uploading coverage report as a PR comment
name: Upload Coverage Comment
on:
  workflow_run:
    workflows: ["Check Coverage Report"]
    types:
      - completed

jobs:
  upload_coverage_comment:
    name: Upload Coverage Report Comment
    permissions:
      pull-requests: write
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: Check Coverage Report
          name: final-coverage-report
          
      - name: Get PR number
        id: get-pr-number
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const run = await github.rest.actions.getWorkflowRun({
              owner,
              repo,
              run_id: context.payload.workflow_run.id,
            });
            const pr = run.data.pull_requests[0];
            if (!pr) {
              core.setFailed('No PR found');
              return;
            }
            core.setOutput('number', pr.number);

      - name: Upload Coverage Report as PR Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ steps.get-pr-number.outputs.number }}
          body-path: 'CoverageReport.md'